name: Serenity API Tests

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build and Run Tests
	  run: mvn -B clean verify -Dweather.api.key=${{ secrets.WEATHER_API_KEY }}
	  env:
	    # This maps the GitHub Secret to an environment variable the runner can see
		WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}

    - name: Upload Serenity Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: serenity-report
        path: target/site/serenity/